---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(Seurat)  
library(tidyverse)
library(CellChat)


control <- readRDS(here("EMT/RDS/cellchat_EMT_control.RDS"))
covid <- readRDS(here("EMT/RDS/cellchat_EMT_covid.RDS"))
ipf <- readRDS(here("EMT/RDS/cellchat_EMT_ipf.RDS"))

object_list <- list(Control = control, COVID = covid)
control_covid <- mergeCellChat(object_list, add.names = names(object_list))

object_list <- list(Control = control, IPF = ipf)
control_ipf <- mergeCellChat(object_list, add.names = names(object_list))

object_list <- list(COVID = covid, IPF = ipf)
covid_ipf <- mergeCellChat(object_list, add.names = names(object_list))

object_list <- list(IPF = ipf, COVID = covid)
ipf_covid <- mergeCellChat(object_list, add.names = names(object_list))

```

```{r}
netVisual_diffInteraction(control_covid, weight.scale = T)
netVisual_diffInteraction(control_ipf, weight.scale = T)
netVisual_diffInteraction(covid_ipf, weight.scale = T)
netVisual_diffInteraction(ipf_covid, weight.scale = T)

```

```{r}
rankNet(
  control_covid,
  slot.name = "netP",
  mode = c("comparison", "single"),
  comparison = c(1, 2),
  color.use = NULL,
  stacked = FALSE,
  sources.use = NULL,
  targets.use = NULL,
  do.stat = FALSE,
  cutoff.pvalue = 0.05,
  tol = 0.05,
  thresh = 0.05,
  show.raw = FALSE,
  return.data = FALSE,
  x.rotation = 90,
  title = NULL,
  bar.w = 0.75,
  font.size = 8,
  do.flip = TRUE,
  x.angle = NULL,
  y.angle = 0,
  x.hjust = 1,
  y.hjust = 1,
  axis.gap = FALSE,
  ylim = NULL,
  segments = NULL,
  tick_width = NULL,
  rel_heights = c(0.9, 0, 0.1)
)
```


```{r}
rankNet(control_covid, mode = "comparison", cutoff.pvalue = 0.05, stacked = T, do.stat = TRUE, x.rotation = 90, do.flip = TRUE)
rankNet(control_ipf, mode = "comparison", cutoff.pvalue = 0.05, stacked = T, do.stat = TRUE, x.rotation = 90, do.flip = TRUE)
rankNet(covid_ipf, mode = "comparison", cutoff.pvalue = 0.05, stacked = T, do.stat = TRUE, x.rotation = 90, do.flip = TRUE)
rankNet(ipf_covid, mode = "comparison", cutoff.pvalue = 0.05, stacked = T, do.stat = TRUE, x.rotation = 90, do.flip = TRUE)
```

```{r}
unique(control_covid@DB$interaction$pathway_name)
```

