---
title: "Untitled"
output: html_document
---



```{r setup, include=FALSE}
library(here)
library(Seurat)
library(tidyverse)
library(CellChat)

df <- readRDS(here("EMT/RDS/df.RDS"))


df <- subset(df, subset = new_submain %in% c("AT2", "AT1", "Ciliated cells", "AT1", "Fibroblasts", "Basal cells", "Gobelt cells", "Mast cells", "Smooth Muscle cells"))
#df <- subset(df, subset = new_submain %in% c("AT2", "AT1", "Fibroblasts"))


DefaultAssay(df) <- "RNA"
control <- subset(df, subset = Diagnosis == "Control")
covid <- subset(df, subset = Diagnosis == "COVID")
ipf <- subset(df, subset = Diagnosis == "IPF")

#### subset by each diagnosis
# control
data_input <- GetAssayData(control, assay = "RNA", slot = "data")
Idents(control) <- "new_submain"
labels <- Idents(control)
meta <- data.frame(labels = labels, row.names = names(labels))
cellchat_control <- createCellChat(object = data_input, meta = meta, group.by = "labels")

# covid
data_input <- GetAssayData(covid, assay = "RNA", slot = "data")
Idents(covid) <- "new_submain"
labels <- Idents(covid)
meta <- data.frame(labels = labels, row.names = names(labels))
cellchat_covid <- createCellChat(object = data_input, meta = meta, group.by = "labels")

# ipf
data_input <- GetAssayData(ipf, assay = "RNA", slot = "data")
Idents(ipf) <- "new_submain"
labels <- Idents(ipf)
meta <- data.frame(labels = labels, row.names = names(labels))
cellchat_ipf <- createCellChat(object = data_input, meta = meta, group.by = "labels")


#### Add meta 
# control
data_input <- GetAssayData(control, assay = "RNA", slot = "data")
Idents(control) <- "new_submain"
labels <- Idents(control)
meta <- data.frame(labels = labels, row.names = names(labels))
cellchat_control <- createCellChat(object = data_input, meta = meta, group.by = "labels")

# covid
data_input <- GetAssayData(covid, assay = "RNA", slot = "data")
Idents(covid) <- "new_submain"
labels <- Idents(covid)
meta <- data.frame(labels = labels, row.names = names(labels))
cellchat_covid <- createCellChat(object = data_input, meta = meta, group.by = "labels")

# ipf
data_input <- GetAssayData(ipf, assay = "RNA", slot = "data")
Idents(ipf) <- "new_submain"
labels <- Idents(ipf)
meta <- data.frame(labels = labels, row.names = names(labels))
cellchat_ipf <- createCellChat(object = data_input, meta = meta, group.by = "labels")


# Calculate the aggregated cell-cell communication network
CellChatDB <- CellChatDB.human
showDatabaseCategory(CellChatDB)
CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling") # use Secreted Signaling

cellchat_control@DB <- CellChatDB.use
cellchat_covid@DB <- CellChatDB.use
cellchat_ipf@DB <- CellChatDB.use

cellchat_control <- subsetData(cellchat_control) 
cellchat_covid <- subsetData(cellchat_covid) 
cellchat_ipf <- subsetData(cellchat_ipf) 

cellchat_control <- identifyOverExpressedGenes(cellchat_control)
cellchat_covid <- identifyOverExpressedGenes(cellchat_covid)
cellchat_ipf <- identifyOverExpressedGenes(cellchat_ipf)

cellchat_control <- identifyOverExpressedInteractions(cellchat_control)
cellchat_covid <- identifyOverExpressedInteractions(cellchat_covid)
cellchat_ipf <- identifyOverExpressedInteractions(cellchat_ipf)

cellchat_control <- projectData(cellchat_control, PPI.human)
cellchat_covid <- projectData(cellchat_covid, PPI.human)
cellchat_ipf <- projectData(cellchat_ipf, PPI.human)

cellchat_control <- computeCommunProb(cellchat_control)
cellchat_covid <- computeCommunProb(cellchat_covid)
cellchat_ipf <- computeCommunProb(cellchat_ipf)

cellchat_control <- filterCommunication(cellchat_control, min.cells = 100)
cellchat_covid <- filterCommunication(cellchat_covid, min.cells = 100)
cellchat_ipf <- filterCommunication(cellchat_ipf, min.cells = 100)

cellchat_control <- computeCommunProbPathway(cellchat_control)
cellchat_covid <- computeCommunProbPathway(cellchat_covid)
cellchat_ipf <- computeCommunProbPathway(cellchat_ipf)

cellchat_control <- aggregateNet(cellchat_control)
cellchat_covid <- aggregateNet(cellchat_covid)
cellchat_ipf <- aggregateNet(cellchat_ipf)
```

```{r}
```


```{r}
object_list <- list(NL = cellchat_control, LS = cellchat_covid)

merge_control_covid <- mergeCellChat(object_list, add.names = (object_list))
```





```{r}
groupSize <- as.numeric(table(cellchat_control@idents))
netVisual_circle(cellchat_control@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Control cell-cell interactions")

groupSize <- as.numeric(table(cellchat_covid@idents))
netVisual_circle(cellchat_covid@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "COVID-19 cell-cell interactions")

groupSize <- as.numeric(table(cellchat_ipf@idents))
netVisual_circle(cellchat_ipf@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "IPF cell-cell interactions")
```
```{r}

mat <- cellchat_control@net$weight
par(mfrow = c(3,4), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}

mat <- cellchat_covid@net$weight
par(mfrow = c(3,4), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}


mat <- cellchat_ipf@net$weight
par(mfrow = c(3,4), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}



cellchat_control@DB$interaction$pathway_name
```







