library(here)
library(tidyverse)
library(Seurat)

df <- readRDS(here('explore/RDS/df.RDS'))
df <- subset(df, subset = cell_type_submain != c("Mesothelial Cell"))

df$row <- substr(rownames(df@meta.data), 1, 6)

df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01157"), "HC1", "NA")
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01174"), "HC2", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01365"), "HC3", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01366"), "HC4", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01367"), "HC5", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("HD65_A", "HD65_C", "HD65_G", "HD65_T"), "HC6", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("HD66_A", "HD66_C", "HD66_G", "HD66_T"), "HC7", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("HD67_A", "HD67_C", "HD67_G", "HD67_T"), "HC8", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("HD68_A", "HD68_C", "HD68_G", "HD68_T"), "HC9", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F00409"), "HC10", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("HD70_A", "HD70_C", "HD70_G", "HD70_T"), "HC11", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01394"), "HC12", df@meta.data$Diagnosis_tag)

df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F00431"), "I1", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01302"), "I2", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01303"), "I3", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01214"), "I4", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01172"), "I5", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01173"), "I6", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01379"), "I7", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01380"), "I8", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("ILD53_"), "I9", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("ILD59-"), "I10", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("ILD60-"), "I10", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("ILD61-"), "I11", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("ILD63_"), "I12", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01390"), "I13", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01391"), "I14", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("F01392"), "I15", df@meta.data$Diagnosis_tag)

df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("obj1_A", "obj1_C", "obj1_G", "obj1_T"), "C1_1", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("obj2_A", "obj2_C", "obj2_G", "obj2_T"), "C1_2", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("obj3_A", "obj3_C", "obj3_G", "obj3_T"), "C1_3", df@meta.data$Diagnosis_tag)
df@meta.data$Diagnosis_tag <- ifelse(df@meta.data$row %in% c("obj4_A", "obj4_C", "obj4_G", "obj4_T"), "C1_4", df@meta.data$Diagnosis_tag)



df@meta.data$cell_type_newmain <- ifelse(df@meta.data$cell_type_submain %in% c("Monocyte", "M2 Macrophage", "M1 Macrophage", "mDCs", "pDCs"), "APC", "NA")
df@meta.data$cell_type_newmain <- ifelse(df@meta.data$cell_type_submain %in% c("Mast Cell"), "Mast", df@meta.data$cell_type_newmain)
df@meta.data$cell_type_newmain <- ifelse(df@meta.data$cell_type_submain %in% c("Neutrophil"), "Neutrophil", df@meta.data$cell_type_newmain)
df@meta.data$cell_type_newmain <- ifelse(df@meta.data$cell_type_submain %in% c("Endothelial Cell"), "Endothelia", df@meta.data$cell_type_newmain)
df@meta.data$cell_type_newmain <- ifelse(df@meta.data$cell_type_submain %in% c("Ciliated Cell", "Club Cell", "Basal Cell", "Gobelt Cell"), "Epithelia", df@meta.data$cell_type_newmain)
df@meta.data$cell_type_newmain <- ifelse(df@meta.data$cell_type_submain %in% c("AT2", "AT1"), "AT", df@meta.data$cell_type_newmain)
df@meta.data$cell_type_newmain <- ifelse(df@meta.data$cell_type_submain %in% c("Plasma Cell", "B Cell"), "B/Plasma", df@meta.data$cell_type_newmain)
df@meta.data$cell_type_newmain <- ifelse(df@meta.data$cell_type_submain %in% c("NK Cell", "CD8 Tcell", "CD4 Tcell"), "T/NK", df@meta.data$cell_type_newmain)
df@meta.data$cell_type_newmain <- ifelse(df@meta.data$cell_type_submain %in% c("Fibroblast Cell"), "Fibroblasts", df@meta.data$cell_type_newmain)
df@meta.data$cell_type_newmain <- ifelse(df@meta.data$cell_type_submain %in% c("Smooth Muscle Cell"), "Smooth Muscle", df@meta.data$cell_type_newmain)


df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Monocyte"), "Monocytes", "NA")
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Mast Cell"), "Mast cells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Neutrophil"), "Neutrophils", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("M2 Macrophage", "M1 Macrophage"), "Macrophages", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("mDCs"), "mDCs", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("pDCs"), "pDCs", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Endothelial Cell"), "Endothelial cells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Ciliated Cell"), "Ciliated cells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Club Cell"), "Club cells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Basal Cell"), "Basal cells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Gobelt Cell"), "Gobelt cells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("AT1"), "AT1", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("AT2"), "AT2", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Plasma Cell"), "Plasma cells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("B Cell"), "B cells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("NK Cell"), "NK cells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("CD8 Tcell"), "CD8 Tcells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("CD4 Tcell"), "CD4 Tcells", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Fibroblast Cell"), "Fibroblasts", df@meta.data$new_submain)
df@meta.data$new_submain <- ifelse(df@meta.data$cell_type_submain %in% c("Smooth Muscle Cell"), "Smooth Muscle cells", df@meta.data$new_submain)

DimPlot(df, group.by = "new_submain", label = T, repel = T) + NoLegend()
ggsave(here("final/figure/DimPlot_total_celltype.pdf"), width = 7, height = 5)


saveRDS(df, file = here("final/RDS/df.RDS"))


