---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(Seurat)
library(tidyverse)
library(here)
library(SingleCellExperiment)
library(cowplot)
library(knitr)
library(sctransform)
library(Matrix)
library(future)
library(future.apply)
```

```{r}
macrophage22 <- readRDS(here('explore/RDS/macrophage2_mindong.RDS'))
```

```{r}
head(macrophage22)
```

```{r}
DimPlot(macrophage22, group.by = "seurat_clusters", label = T, repel = Tz) + NoLegend()
```


```{r}
macrophage2@meta.data$cell_type_submain2 <- ifelse(macrophage2@meta.data$seurat_clusters %in% c(10, 6, 15, 8), "Monocyte", "NA")
macrophage2@meta.data$cell_type_submain2 <- ifelse(macrophage2@meta.data$seurat_clusters %in% c(24, 21, 16, 0, 14, 19, 7, 18, 4, 25, 23), "M1 macrophage2", macrophage2@meta.data$cell_type_submain2)
macrophage2@meta.data$cell_type_submain2 <- ifelse(macrophage2@meta.data$seurat_clusters %in% c(
20, 5, 3, 11, 1, 17, 2, 12, 13), "M2 macrophage2", macrophage2@meta.data$cell_type_submain2)

```

```{r}
DimPlot(macrophage2, group.by = "cell_type_submain2", label = T)
DimPlot(macrophage2, group.by = "cell_type_submain", label = T)
DimPlot(macrophage2, group.by = "Diagnosis", label = T)
DimPlot(macrophage2, group.by = "new_submain2", label = T)

```

```{r}
covid <- subset(macrophage2, subset = Diagnosis == "COVID")
DimPlot(covid, group.by = "Diagnosis", label = T)
```

```{r}
FeaturePlot(macrophage2, features = c("CCL2", "CCL7"))
FeaturePlot(macrophage2, features = c("IL6"))

```


