---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(Signac)
library(Seurat)
library(SeuratWrappers)
library(monocle3)
library(Matrix)
library(ggplot2)
library(patchwork)
library(here)
```

```{r}
macrophage <- readRDS(here('explore/RDS/macrophage_new_marker.RDS'))
```

```{r}
head(macrophage)
```

```{r}
DimPlot(macrophage, group.by = "new_submain", label = T)
DimPlot(macrophage, group.by = "seurat_clusters", label = T)
DimPlot(macrophage, group.by = "new_submain2", label = T)
```

# Building tranjectories with monocle3 
```{r}
macrophage.cds <- as.cell_data_set(macrophage)
macrophage.cds <- cluster_cells(cds = macrophage.cds, reduction_method = "UMAP")
macrophage.cds <- learn_graph(macrophage.cds, use_partition = TRUE)
```

# root cells selection
```{r}
# new submain
root_subset_control <- subset(macrophage, subset = seurat_clusters == 10)
root_subset_control <- root_subset_control@meta.data$X
head(root_subset_control)


# new submain2 
root_subset_covid <- subset(macrophage, subset = seurat_clusters == 10)
root_subset_covid <- root_subset_covid@meta.data$X
head(root_subset_covid)
```

# order cells 
```{r}
control.cds <- order_cells(macrophage.cds, reduction_method = "UMAP", root_cells = root_subset_control)
covid.cds <- order_cells(macrophage.cds, reduction_method = "UMAP", root_cells = root_subset_covid)
```

# plot trajecotires colored by pesudotime 
```{r}
plot_cells(
  cds = control.cds, 
  color_cells_by = "pseudotime",
  show_trajectory_graph = TRUE
)

plot_cells(
  cds = covid.cds, 
  color_cells_by = "pseudotime",
  show_trajectory_graph = TRUE
)


```

```{r}
control.cds <- AddMetaData(
  object = macrophage,
  metadata = control.cds@principal_graph_aux@listData$UMAP$pseudotime,
  col.name = "Control"
)


FeaturePlot(control.cds, c("Control"), pt.size = 0.1) & scale_color_viridis_c()
#ggsave(here('explore_figure/Fig3/Control_monocle.pdf'))
```

```{r}
covid.cds <- AddMetaData(
  object = macrophage,
  metadata = covid.cds@principal_graph_aux@listData$UMAP$pseudotime,
  col.name = "COVID"
)


FeaturePlot(covid.cds, c("COVID"), pt.size = 0.1) & scale_color_viridis_c()
#ggsave(here('explore_figure/Fig3/COVID_monocle.pdf'))
```





