---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(slingshot)
library(BUSpaRse)
library(tidyverse)
library(tidymodels)
library(Seurat)
library(scales)
library(viridis)
library(Matrix)
library(SingleCellExperiment)
library(here)
```


```{r}
refquery <- readRDS(here('explore/RDS/07_df.RDS'))

epi <- subset(refquery, cells = rownames(refquery@meta.data[refquery@meta.data$cell_type_main == "Epithelial cells", ]))
# Subset out only ILD samples from Epi population
epi_ild <- subset(epi, cells = rownames(epi@meta.data[epi@meta.data$Status == "ILD",]))

two <- subset(epi_ild, cells = rownames(epi_ild@meta.data[epi_ild@meta.data$cell_type_submain %in% c("AT1", "AT2"),]))
```

```{r}
two <- RunPCA(two)
tow <- RunUMAP(two, dims = 1:50)
```

```{r}
sce <- as.SingleCellExperiment(tow, assay = "RNA")
```

```{r}
onion <- sce@int_colData$reducedDims@listData$PCA[,1:20]
sce@int_colData$reducedDims@listData$PCA <- onion
```

```{r}
# Remove mitochondria and ribosomal genes
temp <- grep( "^MT-", rownames(sce), ignore.case = F, value = T) 
sce <- sce[!rownames(sce) %in% temp,]
temp2 <- grep( "^RP", rownames(sce), ignore.case = F, value = T) 
sce <- sce[!rownames(sce) %in% temp2,] 
```

```{r}
# Run Slingshot
sce_slingshot <- slingshot(sce, clusterLabels = "cell_type_submain", reducedDim = 'UMAP',
                           start.clus="AT2", end.clus="AT1")
summary(sce_slingshot$slingPseudotime_1)
print(SlingshotDataSet(sce_slingshot))
```

```{r}
	# Plot the trajectory
epi_color <- as.character(tow@meta.data$cell_type_submain)
epi_color <- setNames(epi_color, rownames(tow@meta.data))

onion <- epi_color
onion[onion == "AT2"] <- "#EE7342"
onion[onion == "AT1"] <- "#548BC5"
epi_color <- onion
```

```{r}
plot(reducedDims(sce_slingshot)$UMAP, col = epi_color,
     pch = 16, asp = 1, xlab = "UMAP_1", ylab = "UMAP_2", cex=0.6)   
legend(par(xpd = T), x= "topleft", pch = c(20), 
       legend = c("AT2","AT1"), 
       col = c("#EE7342","#548BC5"), bty = 'n')
lines(slingCurves(sce_slingshot), lwd=3, col = 'black')
```

```{r}
plot(reducedDims(sce_slingshot)$UMAP, col = epi_color,
     pch = 16, asp = 1,  cex=0.6)   
legend(par(xpd = T), x= "topleft", pch = c(20), 
       legend = c("AT2","AT1"), 
       col = c("#EE7342","#548BC5"), bty = 'n')
lines(sce_slingshot, lwd = 2, col = 'black')
```















