---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(slingshot)
library(BUSpaRse)
library(tidyverse)
library(tidymodels)
library(Seurat)
library(scales)
library(viridis)
library(Matrix)
library(SingleCellExperiment)
library(here)
```

```{r}
refquery <- readRDS(here('explore/RDS/07_df.RDS'))
fig3 <- subset(x = refquery, subset = cell_type_submain == "AT2" | cell_type_submain == "AT1")
unique(fig3$cell_type_submain)
```

```{r}
fig3 <- ScaleData(object = fig3)
fig3 <- RunPCA(object = fig3)
fig3 <- FindNeighbors(fig3, dims = 1:30)
fig3 <- FindClusters(fig3)
fig3 <- RunUMAP(object = fig3, dims = 1:30)

DimPlot(fig3, group.by = "seurat_clusters", label = TRUE)
DimPlot(fig3, group.by = "cell_type_submain", label = TRUE)
```

# Convert to SingleCellExperiment
```{r}
sub_sce <- as.SingleCellExperiment(fig3, assay = "RNA")

onion <- sub_sce@int_colData$reducedDims@listData$PCA[,1:20]
sub_sce@int_colData$reducedDims@listData$PCA <- onion

# Remove mitochondria and ribosomal genes
temp <- grep( "^MT-", rownames(sub_sce), ignore.case = F, value = T) 
sub_sce <- sub_sce[!rownames(sub_sce) %in% temp,]
temp2 <- grep( "^RP", rownames(sub_sce), ignore.case = F, value = T) 
sub_sce <- sub_sce[!rownames(sub_sce) %in% temp2,] 
                
# Run Slingshot
sub_slingshot <- slingshot(sub_sce, clusterLabels = "seurat_clusters", reducedDim = 'UMAP',
                           start.clus="6", end.clus = "8")
summary(sub_slingshot$slingPseudotime_1)
print(SlingshotDataSet(sub_slingshot))
```

```{r}

epi_color <- as.character(fig3@meta.data$cell_type_submain)
epi_color <- setNames(epi_color, rownames(fig3@meta.data))

onion <- epi_color
onion[onion == "AT2"] <- "#EE7342"
onion[onion == "AT1"] <- "#548BC5"
epi_color <- onion

plot(reducedDims(sub_slingshot)$UMAP, col = epi_color,
     pch = 16, asp = 1, xlab = "UMAP_1", ylab = "UMAP_2", cex=0.6)   
legend(par(xpd = T), x= "topleft", pch = c(20), 
       legend = c("AT2","AT1"), 
       col = c("#EE7342","#548BC5"), bty = 'n')
#lines(SlingshotDataSet(sub_slingshot)$Lineage3, lwd = 2, col = 'black')
lines(slingCurves(sub_slingshot)$Lineage7, lwd=3, col = 'black')
          
# Save lineage
#umap_lineage <- sub_slingshot$slingPseudotime_1
#umap_lineage <- colnames(sub_slingshot)

#ggsave(here("figure/Trajectory_work/line_UMAP_by_Lineage7.pdf"))
```