---
title: "05_Fibroblast_trajectory"
output: html_document
---

```{r setup, include=FALSE}
library(slingshot)
library(BUSpaRse)
library(tidyverse)
library(tidymodels)
library(Seurat)
library(scales)
library(viridis)
library(Matrix)
library(SingleCellExperiment)
library(here)
```

```{r}
refquery <- readRDS(here('explore/RDS/07_df.RDS'))
```

# Epithelial & Fibroblast 군들에 대해서만 가져오기 
```{r}
two <- subset(x = refquery, subset = cell_type_main == "Epithelial cells" | cell_type_main == "Mesenchymal cells")
unique(two$cell_type_submain)
```

```{r}
two <- ScaleData(object = two)
two <- RunPCA(object = two)
two <- FindNeighbors(two, dims = 1:30)
two <- FindClusters(two)
two <- RunUMAP(object = two, dims = 1:30)
```

```{r}
DimPlot(two, group.by = "seurat_clusters", label = TRUE)
DimPlot(two, group.by = "cell_type_submain", label = TRUE, repel = TRUE, label.size = 3)
```

# Convert to SingleCellExperiment
```{r}
sub_sce <- as.SingleCellExperiment(two, assay = "RNA")

onion <- sub_sce@int_colData$reducedDims@listData$PCA[,1:20]
sub_sce@int_colData$reducedDims@listData$PCA <- onion

# Remove mitochondria and ribosomal genes
temp <- grep( "^MT-", rownames(sub_sce), ignore.case = F, value = T) 
sub_sce <- sub_sce[!rownames(sub_sce) %in% temp,]
temp2 <- grep( "^RP", rownames(sub_sce), ignore.case = F, value = T) 
sub_sce <- sub_sce[!rownames(sub_sce) %in% temp2,] 
                
# Run Slingshot
sub_slingshot <- slingshot(sub_sce, clusterLabels = "cell_type_submain", reducedDim = 'UMAP',
                           start.clus="AT1", end.clus = "Pathological Fibroblasts")
summary(sub_slingshot$slingPseudotime_1)
print(SlingshotDataSet(sub_slingshot))
```


```{r}

epi_color <- as.character(two@meta.data$cell_type_submain)
epi_color <- setNames(epi_color, rownames(two@meta.data))

onion <- epi_color
onion[onion == "AT2"] <- "#EE4242"
onion[onion == "Ciliated Cell"] <- "#EE7042"
onion[onion == "Club Cell"] <- "#EEB542"
onion[onion == "AT1"] <- "#DDEE42"
onion[onion == "Adventitial Fibroblasts"] <- "#E8EE42"
onion[onion == "Basal Cell"] <- "#B5EE42"
onion[onion == "Mesothelial Cell"] <- "#42EE5C"
onion[onion == "Gobelt Cel"] <- "#42EEC9"
onion[onion == "Myofibroblasts"] <- "#42ACEE"
onion[onion == "Airway smooth muscle"] <- "#5642EE"
onion[onion == "Pathological Fibroblasts"] <- "#B242EE"
onion[onion == "Alveolar Fibroblasts"] <- "#EE42C9"
onion[onion == "Vascular smooth muscle"] <- "#EE4273"
onion[onion == "Lipo Fibroblasts"] <- "#EE4253"

epi_color <- onion
```

```{r}
plot(reducedDims(sub_slingshot)$UMAP, col = epi_color,
     pch = 16, asp = 1, xlab = "UMAP_1", ylab = "UMAP_2", cex=0.6)   
legend(par(xpd = T), x= "topleft", pch = c(20), 
       legend = c("AT2","Ciliated Cell", "Club Cell", "AT1", "Adventitial Fibroblasts", "Basal Cell", "Mesothelial Cell", "Gobelt Cel", "Myofibroblasts", "Airway smooth muscle", "Pathological Fibroblasts", "Alveolar Fibroblasts", "Vascular smooth muscle", "Lipo Fibroblasts"), 
       col = c("#EE4242","#EE7042", "#EEB542", "#DDEE42", "#E8EE42", "#B5EE42", "#42EE5C", "#42EEC9", "#42ACEE", "#5642EE", "#B242EE", "#EE42C9", "#EE4273", "#EE4253"), bty = 'n')
#lines(SlingshotDataSet(sub_slingshot)$Lineage3, lwd = 2, col = 'black')
lines(slingCurves(sub_slingshot)$Lineage4, lwd=3, col = 'black')
          
# Save lineage
#umap_lineage <- sub_slingshot$slingPseudotime_1
#umap_lineage <- colnames(sub_slingshot)

#ggsave(here("figure/Trajectory_work/line_UMAP_by_Lineage7.pdf"))
```







