---
title: "covid_qc_process"
output: html_document
---

```{r setup, include=FALSE}
library(Seurat)
library(here)
library(tidyverse)
library(cowplot)
```

```{r}
# Load the IPF dataset by Read10X

setwd("~/R/scRNA_IPF_data/data")
covid_data <- Read10X(data.dir = 'GSE149689_covid_kaist/GSE149689/', gene.column=1) 

# gene.colum = 1 을 하기 전에는 Error in `[.data.frame`(feature.names, , gene.column) :    undefined columns selected error 발생 
# no second column in your genes.tsv file 일수도 있기에 -> gene.colum = 1 을 통해서 Read10X 생성 
# 압축되어있는 파일 상태로 다운 받아본 다음에 다시 진행 
```

```{r}
# IPF data와 동일하게 min,feautures 지정해줘서 진행 
covid <- CreateSeuratObject(covid_data,
                            project = "scRNA_covid",
                            min.features = 200)
```

```{r}
head(covid)
dim(covid)

# meta.data feauture가 현저히 작은 것 확인 가능 
```

```{r}
cell_barcodes <- rownames(covid@meta.data)

covid$sample <- covid@meta.data %>% 
  mutate(cell_barcodes = rownames(.)) %>% 
  mutate(sample = str_sub(cell_barcodes, 18)) %>% select(sample) 

head(covid)
```

```{r}
# sample이라는 새로운 feature가 형성이 되었으니 여기서 필요한 데이터만 추출하기 -> 필요없는 데이터들은 전부다 삭제 
#   5 6 7 8  13 14 19 
covid <- covid %>% 
  subset(sample != "3")

covid <- covid %>% 
  subset(sample != "4")

covid <- covid %>% 
  subset(sample != "5")

covid <- covid %>% 
  subset(sample != "6")

covid <- covid %>% 
  subset(sample != "7")

covid <- covid %>% 
  subset(sample != "8")

covid <- covid %>% 
  subset(sample != "13")

covid <- covid %>% 
  subset(sample != "14")

covid <- covid %>% 
  subset(sample != "19")

unique(covid$sample)

```

```{r}
# orig.ident를 통해서 covid 환자만 남아있는지에 대해서 다시 한번 확인 
unique(covid$orig.ident)
```


```{r}
dim(covid)

# feature들 삭제하기 전에는 dim -> 33538 76529 
# 삭제후: 33538 41548 
```

```{r}
# 이후 reference가 진행한 방법 그대로 QC 진행 
# 우선 percent.mt라는 새로운 feature 형성해주도록 한다 ( tutorial 방법 참고 )
#covid <- PercentageFeatureSet(covid, pattern = "^MT-", col.name = "percent.mt")
head(covid)
```

```{r}
covid <- PercentageFeatureSet(object = covid, pattern = "^MT-", col.name = "percent.mt")

head(covid)
unique(covid$percent.mt)

# 이미 제거되서 결과가 나온것같음 
```

















