---
title: "IPF_1_data_explore"
output: html_document
---

[ 전체적인 workflow ]

1) Read10X 로 읽어준 다음에 Seurat data format으로 변경해주도록 하기 
2) metadata.csv 파일을 넣어줘서 새로운 feature들 생성해주기 
3) 이후 QC 진행한 이후 integration 준비해주도록 하기 

```{r setup, include=FALSE}
library(Seurat)
library(here)
library(tidyverse)
library(ggplot2)
library(cowplot)
library(knitr)
library(dplyr)
library(plyr)
library(BiocManager)
library(sctransform)
library(glmGamPoi)
```

```{r}
# Load the IPF dataset by Read10X

setwd("~/R/scRNA_IPF_data/data/GSE135893_IPF_1")
ild_data <- Read10X(data.dir = 'GSE135893_seurat/', gene.column=1) 

# gene.colum = 1 을 하기 전에는 Error in `[.data.frame`(feature.names, , gene.column) :    undefined columns selected error 발생 
# no second column in your genes.tsv file 일수도 있기에 -> gene.colum = 1 을 통해서 Read10X 생성 
# 압축되어있는 파일 상태로 다운 받아본 다음에 다시 진행 
```

```{r}
# make a SeuratObject 
ild <- CreateSeuratObject(ild_data,
                          project = "scRNA lung",
                          min.features = 200)

# Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')

```
```{r}
metadata <- read_csv("metadata.csv")
metadata 
```
```{r}
ild@meta.data
```
```{r}
ild <- AddMetaData(ild, rownames(ild@meta.data), col.name = "cellbarcodes")
ild@meta.data
```

```{r}
ild <- subset(x = ild, subset = cellbarcodes %in% metadata$cellbarcodes)
```
```{r}
cells <- ild@meta.data
cells <- cells %>% left_join(metadata %>% select(Diagnosis, Sample_Name, Sample_Source, Status, celltype, population, cellbarcodes), by = "cellbarcodes")
cells
```

```{r}
ild <- AddMetaData(ild, cells$Diagnosis, col.name = "Diagnosis")
ild <- AddMetaData(ild, cells$Sample_Name, col.name = "Sample_Name")
ild <- AddMetaData(ild, cells$Sample_Source, col.name = "Sample_Source")
ild <- AddMetaData(ild, cells$Status, col.name = "Status")
ild <- AddMetaData(ild, cells$celltype, col.name = "celltype")
ild <- AddMetaData(ild, cells$population, col.name = "population")
ild@meta.data
```

```{r}
ild <- SCTransform(object = ild, , method = "glmGamPoi", verbose = T)
```

```{r}
head(ild)
```

```{r}
unique(ild$Diagnosis)
# 이미 metadata를 투입하고 제거를 해준 것들이기 때문에 IPF Control 만 남게되는것 
```











