---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(Signac)
library(Seurat)
library(SeuratWrappers)
library(monocle3)
library(Matrix)
library(ggplot2)
library(patchwork)
library(here)
```

```{r}
refquery <- readRDS(here('explore/RDS/07_df.RDS'))

AT <- subset(x = refquery, subset = cell_type_submain == "AT2" | cell_type_submain == "AT1")
rm(refquery)
# subclustering
AT <- ScaleData(object = AT)
AT <- RunPCA(object = AT)
AT <- FindNeighbors(AT, dims = 1:30)
AT <- FindClusters(AT, resolution = 0.6)
AT <- RunUMAP(object = AT, dims = 1:30)

AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(6), "AT1_SC1", "NA")
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(7), "AT1_SC2", AT@meta.data$new_submain)
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(9), "AT1_SC3", AT@meta.data$new_submain)

AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(10), "AT2_SC1", AT@meta.data$new_submain)
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(8), "AT2_SC2", AT@meta.data$new_submain)
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(5), "AT2_SC3", AT@meta.data$new_submain)
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(1), "AT2_SC4", AT@meta.data$new_submain)
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(2), "AT2_SC5", AT@meta.data$new_submain)
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(4), "AT2_SC6", AT@meta.data$new_submain)
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(3), "AT2_SC7", AT@meta.data$new_submain)
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(0), "AT2_SC8", AT@meta.data$new_submain)
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(11), "AT2_SC9", AT@meta.data$new_submain)
AT@meta.data$new_submain <- ifelse(AT@meta.data$seurat_clusters %in% c(12), "AT2_SC10", AT@meta.data$new_submain)

```

```{r}
control <- subset(AT, subset = Diagnosis == "Control")
covid <- subset(AT, subset = Diagnosis == "COVID")
ipf <- subset(AT, subset = Diagnosis == "IPF")
```

```{r}
unique(control$new_submain)
unique(covid$new_submain)
unique(ipf$new_submain)

DimPlot(control, group.by = "new_submain", label = T)
DimPlot(covid, group.by = "new_submain", label = T)
DimPlot(ipf, group.by = "new_submain", label = T)

```

# Building tranjectories with monocle3 
```{r}
control.cds <- as.cell_data_set(control)
control.cds <- cluster_cells(cds = control.cds, reduction_method = "UMAP")
control.cds <- learn_graph(control.cds, use_partition = TRUE)

covid.cds <- as.cell_data_set(covid)
covid.cds <- cluster_cells(cds = covid.cds, reduction_method = "UMAP")
covid.cds <- learn_graph(covid.cds, use_partition = TRUE)

ipf.cds <- as.cell_data_set(ipf)
ipf.cds <- cluster_cells(cds = ipf.cds, reduction_method = "UMAP")
ipf.cds <- learn_graph(ipf.cds, use_partition = TRUE)
```

# root cells selection
```{r}
root_subset_control <- subset(control, subset = new_submain == "AT2_SC1")
root_subset_control <- root_subset_control@meta.data$X
head(root_subset_control)

root_subset_covid <- subset(covid, subset = new_submain == "AT2_SC1")
root_subset_covid <- root_subset_covid@meta.data$X
head(root_subset_covid)

root_subset_ipf <- subset(ipf, subset = new_submain == "AT2_SC1")
root_subset_ipf <- root_subset_ipf@meta.data$X
head(root_subset_ipf)
```
# order cells 
```{r}
control.cds <- order_cells(control.cds, reduction_method = "UMAP", root_cells = root_subset_control)
covid.cds <- order_cells(covid.cds, reduction_method = "UMAP", root_cells = root_subset_covid)
ipf.cds <- order_cells(ipf.cds, reduction_method = "UMAP", root_cells = root_subset_ipf)
```

# plot trajecotires colored by pesudotime 
```{r}
plot_cells(
  cds = control.cds, 
  color_cells_by = "pseudotime",
  show_trajectory_graph = TRUE
)

plot_cells(
  cds = covid.cds, 
  color_cells_by = "pseudotime",
  show_trajectory_graph = TRUE
)

plot_cells(
  cds = ipf.cds, 
  color_cells_by = "pseudotime",
  show_trajectory_graph = TRUE
)
```

```{r}
control.cds <- AddMetaData(
  object = control,
  metadata = control.cds@principal_graph_aux@listData$UMAP$pseudotime,
  col.name = "Control"
)


FeaturePlot(control.cds, c("Control"), pt.size = 0.1) & scale_color_viridis_c()
ggsave(here('explore_figure/Fig3/Control_monocle.pdf'))
```

```{r}
covid.cds <- AddMetaData(
  object = covid,
  metadata = covid.cds@principal_graph_aux@listData$UMAP$pseudotime,
  col.name = "COVID"
)


FeaturePlot(covid.cds, c("COVID"), pt.size = 0.1) & scale_color_viridis_c()
ggsave(here('explore_figure/Fig3/COVID_monocle.pdf'))
```

```{r}
ipf.cds <- AddMetaData(
  object = ipf,
  metadata = ipf.cds@principal_graph_aux@listData$UMAP$pseudotime,
  col.name = "IPF"
)


FeaturePlot(ipf.cds, c("IPF"), pt.size = 0.1) & scale_color_viridis_c()
ggsave(here('explore_figure/Fig3/IPF_monocle.pdf'))
```


