---
title: "03_Use_findmarkers"
output: html_document
---

```{r}
library(slingshot)
library(BUSpaRse)
library(tidyverse)
library(tidymodels)
library(Seurrefquery)
library(scales)
library(viridis)
library(Mrefqueryrix)
library(SingleCellExperiment)
library(here)
```

```{r}
refquery <- readRDS(here('explore/RDS/07_df.RDS'))
```

```{r}
refquery <- subset(x = refquery, subset = cell_type_submain == "AT1" | cell_type_submain == "AT2")
```

```{r}
head(refquery)
```


```{r}
unique(refquery$integrated_snn_res.0.8)
```

```{r}
AT_markers3 <- FindMarkers(refquery, ident.1 = 3, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(AT_markers3, "AT_markers3.csv")

AT_markers22 <- FindMarkers(refquery, ident.1 = 22, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(AT_markers22, "AT_markers22.csv")

AT_markers10 <- FindMarkers(refquery, ident.1 = 10, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(AT_markers10, "AT_markers10.csv")

AT_markers29 <- FindMarkers(refquery, ident.1 = 29, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(AT_markers29, "AT_markers29.csv")

AT_markers33 <- FindMarkers(refquery, ident.1 = 33, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(AT_markers33, "AT_markers33.csv")

AT_markers14 <- FindMarkers(refquery, ident.1 = 14, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(AT_markers14, "AT_markers14.csv")

AT_markers21 <- FindMarkers(refquery, ident.1 = 21, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(AT_markers21, "AT_markers21.csv")

AT_markers2 <- FindMarkers(refquery, ident.1 = 2, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(AT_markers2, "AT_markers2.csv")

AT_markers17 <- FindMarkers(refquery, ident.1 = 17, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(AT_markers17, "AT_markers17.csv")

AT_markers28 <- FindMarkers(refquery, ident.1 = 28, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(AT_markers28, "AT_markers28.csv")
```



```{r}
merge <- rbind(AT_markers2, 
               AT_markers3, 
               AT_markers10, 
               AT_markers14,
               AT_markers17,
               AT_markers21,
               AT_markers22,
               AT_markers29,
               AT_markers33
               )
head(merge)
write.csv(merge, "AT_merge.csv")

```


```{r}
merge <- read.csv(here("explore/Figure_workflow/Gene_Ontology/AT_merge.csv"))
head(merge, n = 5)
```

```{r}
merge %>%
    slice_max(n = 100, order_by = avg_log2FC)
```

```{r}
FeaturePlot()
```














