---
title: "04_Heatmap"
output: html_document
---

```{r}
library(slingshot)
library(BUSpaRse)
library(tidyverse)
library(tidymodels)
library(Seurat)
library(scales)
library(viridis)
library(here)
```

```{r}
refquery <- readRDS(here('explore/RDS/07_df.RDS'))

refquery <- subset(x = refquery, subset = cell_type_submain == "AT1" | cell_type_submain == "AT2")
```

```{r}
AT_genes <- c(
'SCGB1A13',
'BPIFB12',
'SCGB3A13',
'SCGB1A15',
'S100A23',
'SCGB3A15',
'BPIFB14',
'GRP2',
'KRT173',
'SERPIND13',
'CAV16',
'SFTPA21',
'GRP3',
'TFF31',
'LCN22',
'MUC5B',
'CTSB4',
'AGER6',
'SFTPA11',
'KRT175',
'SPP1',
'BPIFA1',
'IGFBP75',
'EMP26',
'CAPS',
'CCL5',
'S100A81',
'TMEM1901',
'KRT152',
'S100A82',
'TFF33',
'KRT5',
'NKG7',
'MMP75',
'IL325',
'KRT74',
'BPIFA11',
'CALCA1',
'RTKN26',
'PRSS26',
'MSMB',
'SFTPC1',
'TMEM190',
'CAPS2',
'CYP4B15',
'LCN23',
'TSPAN1',
'C20orf85',
'CXCL144',
'SERPINB3',
'C9orf24',
'S100A8',
'PGC1',
'SAA11',
'IGFBP25',
'FAM183A',
'TAGLN5',
'CP1',
'CCL4',
'MT1X3',
'TIMP35',
'CEACAM66',
'WFDC22',
'IGFBP24',
'TSPAN8',
'IFI275',
'DNAH12',
'C2orf401',
'TSPAN16',
'CD52',
'FN15',
'CAV26',
'TMEM45A',
'CXCL6',
'MMP1',
'S100A93',
'LMO76',
'CCL4L2',
'GSTA11',
'LGALS7B',
'MYL96',
'C20orf851',
'MMP73',
'CCL183',
'C1orf194',
'MT2A3',
'SAA12',
'CXCL16',
'CXCL81',
'LYZ4',
'LTF',
'IL1RN',
'LRRK21',
'PIFO',
'GRP',
'SOX46',
'MDK6',
'IGFBP2',
'SLPI2')

```

```{r}
DoHeatmap(refquery, 
          features = AT_genes,
          group.by = "cell_type_submain",
          angle = 45)
```











