---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(Seurat)
library(here)
library(tidyverse)
library(cowplot)
library(knitr)

library(BiocManager)
library(sctransform)
library(glmGamPoi)
library(Matrix)
library(future)
library(future.apply)
```

```{r}
pathway <- readRDS(here("explore/RDS/07_df.RDS"))
```

# 1. TGF-B pathway 
```{r}
FeaturePlot(pathway, features = c(
'ACVR1',
'ACVR1C',
'ACVR2A',
'ACVR2B',
'ACVRL1',
'AMH',
'AMHR2',
'BMP2',
'BMP4',
'BMP5',
'BMP6',
'BMP7',
'BMP8A',
'BMP8B',
'BMPR1A',
'BMPR1B',
'BMPR2',
'CDKN2B',
'CHRD',
'COMP',
'CREBBP',
'CUL1',
'DCN',
'E2F4',
'E2F5',
'EP300',
'FST',
'GDF5',
'GDF6',
'GDF7',
'ID1',
'ID2',
'ID3',
'ID4',
'IFNG',
'INHBA',
'INHBB',
'INHBC',
'INHBE',
'LEFTY1',
'LEFTY2',
'LTBP1',
'MAPK1',
'MAPK3',
'MYC',
'NODAL',
'NOG',
'PITX2',
'PPP2CA',
'PPP2CB',
'PPP2R1A',
'PPP2R1B',
'RBL1',
'RBL2',
'RBX1',
'RHOA',
'ROCK1',
'ROCK2',
'RPS6KB1',
'RPS6KB2',
'SKP1',
'SKP1P2',
'SMAD1',
'SMAD2',
'SMAD3',
'SMAD4',
'SMAD5',
'SMAD6',
'SMAD7',
'SMAD9',
'SMURF1',
'SMURF2',
'SP1',
'TFDP1',
'TGFB1',
'TGFB2',
'TGFB3',
'TGFBR1',
'TGFBR2',
'THBS1',
'THBS2',
'THBS3',
'THBS4',
'TNF',
'ZFYVE16',
'ZFYVE9'
))
```

# 2. WNT-patwhay 
```{r}
FeaturePlot(pathway, features = c(
'APC',
'APC2',
'AXIN1',
'AXIN2',
'BTRC',
'CACYBP',
'CAMK2A',
'CAMK2B',
'CAMK2D',
'CAMK2G',
'CCND1',
'CCND2',
'CCND3',
'CER1',
'CHD8',
'CHP1',
'CHP2',
'CREBBP',
'CSNK1A1',
'CSNK1A1L',
'CSNK1E',
'CSNK2A1',
'CSNK2A2',
'CSNK2B',
'CTBP1',
'CTBP2',
'CTNNB1',
'CTNNBIP1',
'CUL1',
'CXXC4',
'DAAM1',
'DAAM2',
'DKK1',
'DKK2',
'DKK4',
'DVL1',
'DVL2',
'DVL3',
'EP300',
'FBXW11',
'FOSL1',
'FRAT1',
'FRAT2',
'FZD1',
'FZD10',
'FZD2',
'FZD3',
'FZD4',
'FZD5',
'FZD6',
'FZD7',
'FZD8',
'FZD9',
'GSK3B',
'JUN',
'LEF1',
'LRP5',
'LRP6',
'MAP3K7',
'MAPK10',
'MAPK8',
'MAPK9',
'MMP7',
'MYC',
'NFAT5',
'NFATC1',
'NFATC2',
'NFATC3',
'NFATC4',
'NKD1',
'NKD2',
'NLK',
'PLCB1',
'PLCB2',
'PLCB3',
'PLCB4',
'PORCN',
'PPARD',
'PPP2CA',
'PPP2CB',
'PPP2R1A',
'PPP2R1B',
'PPP2R5A',
'PPP2R5B',
'PPP2R5C',
'PPP2R5D',
'PPP2R5E',
'PPP3CA',
'PPP3CB',
'PPP3CC',
'PPP3R1',
'PPP3R2',
'PRICKLE1',
'PRICKLE2',
'PRKACA',
'PRKACB',
'PRKACG',
'PRKCA',
'PRKCB',
'PRKCG',
'PRKX',
'PSEN1',
'RAC1',
'RAC2',
'RAC3',
'RBX1',
'RHOA',
'ROCK1',
'ROCK2',
'RUVBL1',
'SENP2',
'SFRP1',
'SFRP2',
'SFRP4',
'SFRP5',
'SIAH1',
'SKP1',
'SKP1P2',
'SMAD2',
'SMAD3',
'SMAD4',
'SOX17',
'TBL1X',
'TBL1XR1',
'TBL1Y',
'TCF7',
'TCF7L1',
'TCF7L2',
'TP53',
'VANGL1',
'VANGL2',
'WIF1',
'WNT1',
'WNT10A',
'WNT10B',
'WNT11',
'WNT16',
'WNT2',
'WNT2B',
'WNT3',
'WNT3A',
'WNT4',
'WNT5A',
'WNT5B',
'WNT6',
'WNT7A',
'WNT7B',
'WNT8A',
'WNT8B',
'WNT9A',
'WNT9B'
))
```

# 3. NOTCH pathway 
```{r}
FeaturePlot(pathway, features = c(
'ADAM17',
'APH1A',
'CIR1',
'CREBBP',
'CTBP1',
'CTBP2',
'DLL1',
'DLL3',
'DLL4',
'DTX1',
'DTX2',
'DTX3',
'DTX3L',
'DTX4',
'DVL1',
'DVL2',
'DVL3',
'EP300',
'HDAC1',
'HDAC2',
'HES1',
'HES5',
'JAG1',
'JAG2',
'KAT2A',
'KAT2B',
'LFNG',
'MAML1',
'MAML2',
'MAML3',
'MFNG',
'NCOR2',
'NCSTN',
'NOTCH1',
'NOTCH2',
'NOTCH3',
'NOTCH4',
'NUMB',
'NUMBL',
'PSEN1',
'PSEN2v',
'PSENEN',
'PTCRA',
'RBPJ',
'RBPJL',
'RFNGv',
'SNW1v'
))
```

```{r}
FeaturePlot(pathway, features = c("HES1", "PSEN2", "PSENEN", "RFNG", "SNW1", "MAML3"), raster=FALSE)
```

