---
title: "02_TGF_Beta"
output: html_document
---

```{r setup, include=FALSE}
library(Seurat)
library(here)
library(tidyverse)
library(cowplot)
library(knitr)

library(BiocManager)
library(sctransform)
library(glmGamPoi)
library(Matrix)
library(future)
library(future.apply)
```

```{r}
plan('multiprocess', workers = 20)
options(future.globals.maxSize = 2e+05 * 1024^2)
```

```{r}
pathway <- readRDS(here("explore/RDS/pathway.RDS"))
```

```{r}
FeaturePlot(pathway, features = c(
'ACVR1',
'ACVR1C',
'ACVR2A',
'ACVR2B',
'ACVRL1',
'AMH',
'AMHR2',
'BMP2',
'BMP4',
'BMP5'))
```

```{r}
FeaturePlot(pathway, features = c(
'BMP6',
'BMP7',
'BMP8A',
'BMP8B',
'BMPR1A',
'BMPR1B',
'BMPR2',
'CDKN2B',
'CHRD',
'COMP'))
```

```{r}
FeaturePlot(pathway, features = c(
'CREBBP',
'CUL1',
'DCN',
'E2F4',
'E2F5',
'EP300',
'FST',
'GDF5',
'GDF6',
'GDF7'))
```

```{r}
FeaturePlot(pathway, features = c(
'ID1',
'ID2',
'ID3',
'ID4',
'IFNG',
'INHBA',
'INHBB',
'INHBC',
'INHBE',
'LEFTY1'))
```

```{r}
FeaturePlot(pathway, features = c(
'LEFTY2',
'LTBP1',
'MAPK1',
'MAPK3',
'MYC',
'NODAL',
'NOG',
'PITX2',
'PPP2CA',
'PPP2CB'))
```

```{r}
FeaturePlot(pathway, features = c(
'PPP2R1A',
'PPP2R1B',
'RBL1',
'RBL2',
'RBX1',
'RHOA',
'ROCK1',
'ROCK2',
'RPS6KB1',
'RPS6KB2'))
```

```{r}
FeaturePlot(pathway, features = c(
'SKP1',
'SKP1P2',
'SMAD1',
'SMAD2',
'SMAD3',
'SMAD4',
'SMAD5',
'SMAD6',
'SMAD7',
'SMAD9',
'SMURF1',
'SMURF2',
'SP1',
'TFDP1',
'TGFB1'))
```


```{r}
FeaturePlot(pathway, features = c(
'TGFB2',
'TGFB3',
'TGFBR1',
'TGFBR2',
'THBS1',
'THBS2',
'THBS3',
'THBS4',
'TNF',
'ZFYVE16',
'ZFYVE9'
  ))
```

# Notch 

```{r}
FeaturePlot(pathway, features = c(
'ADAM17',
'APH1A',
'CIR1',
'CREBBP',
'CTBP1',
'CTBP2',
'DLL1',
'DLL3',
'DLL4',
'DTX1',
'DTX2',
'DTX3',
'DTX3L',
'DTX4',
'DVL1',
'DVL2',
'DVL3',
'EP300',
'HDAC1',
'HDAC2',
'HES1',
'HES5',
'JAG1',
'JAG2',
'KAT2A',
'KAT2B',
'LFNG',
'MAML1',
'MAML2',
'MAML3',
'MFNG',
'NCOR2',
'NCSTN',
'NOTCH1',
'NOTCH2',
'NOTCH3',
'NOTCH4',
'NUMB',
'NUMBL',
'PSEN1',
'PSEN2',
'PSENEN',
'PTCRA',
'RBPJ',
'RBPJL',
'RFNG',
'SNW1'
))
```











