---
title: "Untitled"
output: html_document
---


```{r setup, include=FALSE}
library(Seurat)
library(here)
library(tidyverse)
library(cowplot)
library(knitr)

library(BiocManager)
library(sctransform)
library(glmGamPoi)
library(Matrix)
library(future)
library(future.apply)
```

```{r}
plan('multiprocess', workers = 20)
options(future.globals.maxSize = 2e+05 * 1024^2)
```

```{r}
pathway <- readRDS(here("explore/RDS/pathway.RDS"))
```

```{r}
FeaturePlot(pathway, features = c(
"APC",
'APC2',
'AXIN1',
'AXIN2',
'BTRC',
'CACYBP',
'CAMK2A',
'CAMK2B',
'CAMK2D',
'CAMK2G'))

FeaturePlot(pathway, features = c(
'CCND1',
'CCND2',
'CCND3',
'CER1',
'CHD8',
'CHP1',
'CHP2',
'CREBBP',
'CSNK1A1',
'CSNK1A1L'))
```

```{r}
FeaturePlot(pathway, features = c(
'CSNK1E',
'CSNK2A1',
'CSNK2A2',
'CSNK2B',
'CTBP1',
'CTBP2',
'CTNNB1',
'CTNNBIP1',
'CUL1',
'CXXC4'))
```

```{r}
FeaturePlot(pathway, features = c(
'DAAM1',
'DAAM2',
'DKK1',
'DKK2',
'DKK4',
'DVL1',
'DVL2',
'DVL3',
'EP300',
'FBXW11'))
```

```{r}
FeaturePlot(pathway, features = c(
'FOSL1',
'FRAT1',
'FRAT2',
'FZD1',
'FZD10',
'FZD2',
'FZD3',
'FZD4',
'FZD5',
'FZD6'))
```

```{r}
FeaturePlot(pathway, features = c(
'FZD7',
'FZD8',
'FZD9',
'GSK3B',
'JUN',
'LEF1',
'LRP5',
'LRP6',
'MAP3K7',
'MAPK10'
))
```

```{r}
FeaturePlot(pathway, features = c(
'MAPK8',
'MAPK9',
'MMP7',
'MYC',
'NFAT5',
'NFATC1',
'NFATC2',
'NFATC3',
'NFATC4',
'NKD1'))
```

```{r}
FeaturePlot(pathway, features = c(
'NKD2',
'NLK',
'PLCB1',
'PLCB2',
'PLCB3',
'PLCB4',
'PORCN',
'PPARD',
'PPP2CA',
'PPP2CB'))
```

```{r}
FeaturePlot(pathway, features = c(
'PPP2R1A',
'PPP2R1B',
'PPP2R5A',
'PPP2R5B',
'PPP2R5C',
'PPP2R5D',
'PPP2R5E',
'PPP3CA',
'PPP3CB',
'PPP3CC'
))
```

```{r}
FeaturePlot(pathway, features = c(

'PRKCG'
))
```

```{r}
FeaturePlot(pathway, features = c(
'PRKX',
'PSEN1',
'RAC1',
'RAC2',
'RAC3',
'RBX1',
'RHOA',
'ROCK1',
'ROCK2',
'RUVBL1'))
```

```{r}
FeaturePlot(pathway, features = c(
'SENP2',
'SFRP1',
'SFRP2',
'SFRP4',
'SFRP5',
'SIAH1',
'SKP1',
'SKP1P2',
'SMAD2',
'SMAD3'
))
```

```{r}
FeaturePlot(pathway, features = c(
'SMAD4',
'SOX17',
'TBL1X',
'TBL1XR1',
'TBL1Y',
'TCF7',
'TCF7L1',
'TCF7L2',
'TP53',
'VANGL1' 
))
```

```{r}
FeaturePlot(pathway, features = c(
'VANGL2',
'WIF1',
'WNT1',
'WNT10A',
'WNT10B',
'WNT11',
'WNT16',
'WNT2',
'WNT2B',
'WNT3'))
```


```{r}
FeaturePlot(pathway, features = c(
'WNT3A',
'WNT4',
'WNT5A',
'WNT5B',
'WNT6',
'WNT7A',
'WNT7B',
'WNT8A',
'WNT8B',
'WNT9A',
'WNT9B'
  ))
```

